=== carnationcrab/growth/data/core/schemas/biomes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="biomes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="biome" type="BiomeDef" maxOccurs="unbounded"/>
        <xs:element name="biome_plant_spawn_rule" type="BiomePlantSpawnRuleDef" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="BiomeDef">
    <xs:sequence>
      <xs:element name="surface_palette" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="surface_id" type="xs:string" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="spawn_groups" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="plant_group_ref" maxOccurs="unbounded">
              <xs:complexType>
                <xs:attribute name="plant_group_id" type="xs:string" use="required"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="biome_id" type="xs:ID" use="required"/>
    <xs:attribute name="display_name" type="xs:string" use="required"/>
    <xs:attribute name="climate_profile_id" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="BiomePlantSpawnRuleDef">
    <xs:attribute name="biome_id" type="xs:string" use="required"/>
    <xs:attribute name="plant_group_id" type="xs:string" use="required"/>
    <xs:attribute name="weight" type="xs:nonNegativeInteger" use="required"/>
    <xs:attribute name="condition_set_id" type="xs:string" use="optional"/>
    <xs:attribute name="elevation_band_min" type="xs:decimal" use="optional"/>
    <xs:attribute name="elevation_band_max" type="xs:decimal" use="optional"/>
  </xs:complexType>
</xs:schema>

=== carnationcrab/growth/data/core/defs/biomes.xml
<?xml version="1.0" encoding="UTF-8"?>
<biomes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="../schemas/biomes.xsd">
  <biome biome_id="temperate_forest" display_name="Temperate forest" climate_profile_id="climate_temperate">
	<surface_palette>
	  <surface_id>bare_soil</surface_id>
	  <surface_id>tilled</surface_id>
	  <surface_id>mulch</surface_id>
	  <surface_id>rock</surface_id>
	</surface_palette>
	<spawn_groups>
	  <plant_group_ref plant_group_id="forest_understory"/>
	  <plant_group_ref plant_group_id="forest_canopy"/>
	</spawn_groups>
  </biome>
  <biome biome_id="arid_shrubland" display_name="Arid shrubland" climate_profile_id="climate_arid">
	<surface_palette>
	  <surface_id>bare_soil</surface_id>
	  <surface_id>sand</surface_id>
	  <surface_id>rock</surface_id>
	</surface_palette>
	<spawn_groups>
	  <plant_group_ref plant_group_id="shrubland_pioneer"/>
	</spawn_groups>
  </biome>
  <biome_plant_spawn_rule biome_id="temperate_forest" plant_group_id="forest_understory" weight="100"/>
  <biome_plant_spawn_rule biome_id="temperate_forest" plant_group_id="forest_canopy" weight="60"/>
  <biome_plant_spawn_rule biome_id="arid_shrubland" plant_group_id="shrubland_pioneer" weight="80"/>
</biomes>
