=== carnationcrab/growth/data/core/schemas/points_of_interest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="points_of_interest">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="poi" type="POIDef" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="POIDef">
    <xs:sequence>
      <xs:element name="placement" minOccurs="0">
        <xs:complexType>
          <xs:attribute name="condition_set_id" type="xs:string" use="optional"/>
          <xs:attribute name="min_elevation" type="xs:decimal" use="optional"/>
          <xs:attribute name="max_elevation" type="xs:decimal" use="optional"/>
          <xs:attribute name="biome_ids" type="xs:string" use="optional"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="poi_id" type="xs:ID" use="required"/>
    <xs:attribute name="display_name" type="xs:string" use="required"/>
    <xs:attribute name="poi_type" type="xs:string" use="required"/>
    <xs:attribute name="radius_cells" type="xs:nonNegativeInteger" use="optional"/>
    <xs:attribute name="building_id" type="xs:string" use="optional"/>
    <xs:attribute name="prefab_tag" type="xs:string" use="optional"/>
    <xs:attribute name="weight" type="xs:nonNegativeInteger" use="optional" default="1"/>
  </xs:complexType>
</xs:schema>

=== carnationcrab/growth/data/core/stamps/points_of_interest.xml
<?xml version="1.0" encoding="UTF-8"?>
<points_of_interest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:noNamespaceSchemaLocation="../schemas/points_of_interest.xsd">
  <poi poi_id="starting_clearing" display_name="Starting clearing" poi_type="spawn" radius_cells="8" weight="1">
    <placement condition_set_id="flat_enough" min_elevation="0" max_elevation="100" biome_ids="temperate_forest,arid_shrubland"/>
  </poi>
  <poi poi_id="ruined_shed" display_name="Ruined shed" poi_type="structure" radius_cells="3"
       building_id="shed" prefab_tag="stamp_ruined_shed" weight="10">
    <placement min_elevation="0" max_elevation="80" biome_ids="temperate_forest"/>
  </poi>
  <poi poi_id="old_well" display_name="Old well" poi_type="structure" radius_cells="2"
       prefab_tag="stamp_well" weight="15">
    <placement min_elevation="0" max_elevation="120" biome_ids="temperate_forest,arid_shrubland"/>
  </poi>
  <poi poi_id="shrine" display_name="Garden shrine" poi_type="decoration" radius_cells="2"
       prefab_tag="stamp_shrine" weight="5">
    <placement biome_ids="temperate_forest"/>
  </poi>
</points_of_interest>
