=== carnationcrab/growth/data/core/schemas/recipes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="recipes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="recipe" type="RecipeDef" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="RecipeDef">
    <xs:sequence>
      <xs:element name="inputs">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="input" type="RecipeSlotDef" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="outputs">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="output" type="RecipeSlotDef" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="required_station_tags" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="tag" type="xs:string" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="skill_tags" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="tag" type="xs:string" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="recipe_id" type="xs:ID" use="required"/>
    <xs:attribute name="time_to_complete" type="xs:nonNegativeInteger" use="required"/>
  </xs:complexType>

  <xs:complexType name="RecipeSlotDef">
    <xs:attribute name="item_id" type="xs:string" use="required"/>
    <xs:attribute name="qty" type="xs:nonNegativeInteger" use="required"/>
  </xs:complexType>
</xs:schema>

=== carnationcrab/growth/data/core/defs/recipes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- RecipeDef: inputs, outputs, time, required station/skill tags. -->
<recipes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../schemas/recipes.xsd">
  <recipe recipe_id="recipe_compost_bin" time_to_complete="60">
    <inputs>
      <input item_id="item_wood" qty="8"/>
      <input item_id="item_nails" qty="4"/>
    </inputs>
    <outputs>
      <output item_id="item_compost_bin" qty="1"/>
    </outputs>
    <required_station_tags>
      <tag>workbench</tag>
    </required_station_tags>
  </recipe>
  <recipe recipe_id="recipe_rain_barrel" time_to_complete="45">
    <inputs>
      <input item_id="item_wood" qty="4"/>
      <input item_id="item_metal_hoops" qty="2"/>
    </inputs>
    <outputs>
      <output item_id="item_rain_barrel" qty="1"/>
    </outputs>
    <required_station_tags>
      <tag>workbench</tag>
    </required_station_tags>
  </recipe>
  <recipe recipe_id="recipe_shed" time_to_complete="300">
    <inputs>
      <input item_id="item_wood" qty="24"/>
      <input item_id="item_nails" qty="16"/>
      <input item_id="item_roof_tiles" qty="9"/>
    </inputs>
    <outputs>
      <output item_id="item_shed" qty="1"/>
    </outputs>
    <required_station_tags>
      <tag>workbench</tag>
    </required_station_tags>
    <skill_tags>
      <tag>carpentry</tag>
    </skill_tags>
  </recipe>
</recipes>
