=== carnationcrab/growth/data/core/schemas/seasons.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="climate">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="climate_profiles">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="climate_profile" type="ClimateProfileDef" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="season_tables">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="season_table" type="SeasonTableDef" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="seasons">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="season" type="SeasonDef" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="ClimateProfileDef">
    <xs:sequence>
      <xs:element name="temp_curve_id" type="xs:string"/>
      <xs:element name="rain_curve_id" type="xs:string"/>
      <xs:element name="wind_curve_id" type="xs:string"/>
      <xs:element name="humidity_curve_id" type="xs:string"/>
      <xs:element name="season_table_id" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="climate_profile_id" type="xs:ID" use="required"/>
  </xs:complexType>

  <xs:complexType name="SeasonTableDef">
    <xs:sequence>
      <xs:element name="season_ref" type="SeasonRefDef" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="season_table_id" type="xs:ID" use="required"/>
  </xs:complexType>

  <xs:complexType name="SeasonRefDef">
    <xs:attribute name="season_id" type="xs:string" use="required"/>
    <xs:attribute name="start_day_of_year" type="xs:nonNegativeInteger" use="required"/>
  </xs:complexType>

  <xs:complexType name="SeasonDef">
    <xs:attribute name="season_id" type="xs:ID" use="required"/>
    <xs:attribute name="display_name" type="xs:string" use="required"/>
    <xs:attribute name="day_length_hours" type="xs:decimal" use="required"/>
    <xs:attribute name="weather_distribution_id" type="xs:string" use="required"/>
  </xs:complexType>
</xs:schema>

=== carnationcrab/growth/data/core/defs/seasons.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ClimateProfile, SeasonTable, SeasonDef. Reusable across biomes/regions. -->
<climate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../schemas/seasons.xsd">
  <climate_profiles>
    <climate_profile climate_profile_id="climate_temperate">
      <temp_curve_id>curve_temperate_temp</temp_curve_id>
      <rain_curve_id>curve_temperate_rain</rain_curve_id>
      <wind_curve_id>curve_temperate_wind</wind_curve_id>
      <humidity_curve_id>curve_temperate_humidity</humidity_curve_id>
      <season_table_id>seasons_temperate</season_table_id>
    </climate_profile>
    <climate_profile climate_profile_id="climate_arid">
      <temp_curve_id>curve_arid_temp</temp_curve_id>
      <rain_curve_id>curve_arid_rain</rain_curve_id>
      <wind_curve_id>curve_arid_wind</wind_curve_id>
      <humidity_curve_id>curve_arid_humidity</humidity_curve_id>
      <season_table_id>seasons_arid</season_table_id>
    </climate_profile>
  </climate_profiles>
  <season_tables>
    <season_table season_table_id="seasons_temperate">
      <season_ref season_id="spring" start_day_of_year="80"/>
      <season_ref season_id="summer" start_day_of_year="172"/>
      <season_ref season_id="autumn" start_day_of_year="266"/>
      <season_ref season_id="winter" start_day_of_year="356"/>
    </season_table>
    <season_table season_table_id="seasons_arid">
      <season_ref season_id="dry" start_day_of_year="1"/>
      <season_ref season_id="wet" start_day_of_year="182"/>
    </season_table>
  </season_tables>
  <seasons>
    <season season_id="spring" display_name="Spring" day_length_hours="12.5" weather_distribution_id="weather_mild"/>
    <season season_id="summer" display_name="Summer" day_length_hours="15" weather_distribution_id="weather_warm"/>
    <season season_id="autumn" display_name="Autumn" day_length_hours="11" weather_distribution_id="weather_mild"/>
    <season season_id="winter" display_name="Winter" day_length_hours="8" weather_distribution_id="weather_cold"/>
    <season season_id="dry" display_name="Dry season" day_length_hours="12" weather_distribution_id="weather_arid_dry"/>
    <season season_id="wet" display_name="Wet season" day_length_hours="12" weather_distribution_id="weather_arid_wet"/>
  </seasons>
</climate>
