=== carnationcrab/growth/data/core/schemas/surfaces.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="surfaces">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="surface" type="SurfaceDef" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="SurfaceDef">
    <xs:sequence>
      <xs:element name="tags" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="tag" type="xs:string" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="surface_id" type="xs:ID" use="required"/>
    <xs:attribute name="display_name" type="xs:string" use="required"/>
    <xs:attribute name="passable" type="xs:boolean" use="required"/>
    <xs:attribute name="buildable" type="xs:boolean" use="required"/>
    <xs:attribute name="base_move_cost" type="xs:unsignedByte" use="required"/>
    <xs:attribute name="water_infiltration" type="xs:unsignedByte" use="required"/>
    <xs:attribute name="water_retention" type="xs:unsignedByte" use="required"/>
    <xs:attribute name="fertility_modifier" type="xs:short" use="required"/>
    <xs:attribute name="disturbance_modifier" type="xs:short" use="required"/>
    <xs:attribute name="visual_material_tag" type="xs:string" use="required"/>
  </xs:complexType>
</xs:schema>

=== carnationcrab/growth/data/core/defs/surfaces.xml
<?xml version="1.0" encoding="UTF-8"?>
<surfaces xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="../schemas/surfaces.xsd">
  <surface surface_id="bare_soil" display_name="Bare soil" passable="true" buildable="true"
           base_move_cost="1" water_infiltration="200" water_retention="120"
           fertility_modifier="0" disturbance_modifier="0" visual_material_tag="mat_soil">
    <tags><tag>soil</tag></tags>
  </surface>
  <surface surface_id="tilled" display_name="Tilled soil" passable="true" buildable="true"
           base_move_cost="1" water_infiltration="220" water_retention="140"
           fertility_modifier="5" disturbance_modifier="10" visual_material_tag="mat_tilled">
    <tags><tag>soil</tag><tag>tilled</tag></tags>
  </surface>
  <surface surface_id="mulch" display_name="Mulch" passable="true" buildable="false"
           base_move_cost="1" water_infiltration="180" water_retention="160"
           fertility_modifier="10" disturbance_modifier="-5" visual_material_tag="mat_mulch">
    <tags><tag>mulch</tag></tags>
  </surface>
  <surface surface_id="rock" display_name="Rock" passable="false" buildable="false"
           base_move_cost="255" water_infiltration="0" water_retention="0"
           fertility_modifier="0" disturbance_modifier="0" visual_material_tag="mat_rock">
    <tags><tag>rock</tag></tags>
  </surface>
  <surface surface_id="sand" display_name="Sand" passable="true" buildable="true"
           base_move_cost="2" water_infiltration="255" water_retention="20"
           fertility_modifier="-10" disturbance_modifier="0" visual_material_tag="mat_sand">
    <tags><tag>sand</tag></tags>
  </surface>
</surfaces>
