=== carnationcrab/growth/data/core/schemas/terrain_features.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="terrain_features">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="terrain_feature" type="TerrainFeatureDef" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="TerrainFeatureDef">
    <xs:sequence>
      <xs:element name="surface_layer" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="surface_id" type="xs:string" use="required"/>
          <xs:attribute name="depth_min" type="xs:decimal" use="optional"/>
          <xs:attribute name="depth_max" type="xs:decimal" use="optional"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="feature_id" type="xs:ID" use="required"/>
    <xs:attribute name="display_name" type="xs:string" use="required"/>
    <xs:attribute name="area_pattern_id" type="xs:string" use="optional"/>
    <xs:attribute name="radius_cells" type="xs:nonNegativeInteger" use="optional"/>
    <xs:attribute name="elevation_delta" type="xs:decimal" use="optional"/>
    <xs:attribute name="weight" type="xs:nonNegativeInteger" use="optional" default="1"/>
  </xs:complexType>
</xs:schema>

=== carnationcrab/growth/data/core/stamps/terrain_features.xml
<?xml version="1.0" encoding="UTF-8"?>
<terrain_features xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				  xsi:noNamespaceSchemaLocation="../schemas/terrain_features.xsd">
  <terrain_feature feature_id="rock_outcrop_small" display_name="Small rock outcrop" radius_cells="1"
				   elevation_delta="0.2" weight="50">
	<surface_layer surface_id="rock" depth_min="0" depth_max="1"/>
  </terrain_feature>
  <terrain_feature feature_id="rock_outcrop_large" display_name="Rock outcrop" area_pattern_id="pattern_2x2"
				   radius_cells="2" elevation_delta="0.5" weight="20">
	<surface_layer surface_id="rock" depth_min="0" depth_max="1"/>
  </terrain_feature>
  <terrain_feature feature_id="sand_patch" display_name="Sand patch" radius_cells="3"
				   elevation_delta="0" weight="30">
	<surface_layer surface_id="sand" depth_min="0" depth_max="1"/>
  </terrain_feature>
  <terrain_feature feature_id="low_mound" display_name="Low mound" radius_cells="4"
				   elevation_delta="0.3" weight="40">
	<surface_layer surface_id="bare_soil" depth_min="0" depth_max="1"/>
  </terrain_feature>
  <terrain_feature feature_id="mulch_patch" display_name="Mulch patch" radius_cells="2" weight="15">
	<surface_layer surface_id="mulch" depth_min="0" depth_max="1"/>
  </terrain_feature>
</terrain_features>
