=== carnationcrab/growth/data/core/schemas/ui_strings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="ui_strings">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="string" type="UIStringDef" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="locale" type="xs:string" use="optional" default="en-GB"/>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="UIStringDef">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="string_id" type="xs:ID" use="required"/>
        <xs:attribute name="context" type="xs:string" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== carnationcrab/growth/data/core/defs/ui_strings.xml
<?xml version="1.0" encoding="UTF-8"?>
<ui_strings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../schemas/ui_strings.xsd"
            locale="en-GB">
  <string string_id="menu_play">Play</string>
  <string string_id="menu_settings">Settings</string>
  <string string_id="menu_quit">Quit</string>
  <string string_id="menu_resume">Resume</string>
  <string string_id="menu_save">Save</string>
  <string string_id="menu_load">Load</string>
  <string string_id="hud_stamina">Stamina</string>
  <string string_id="hud_time">Time</string>
  <string string_id="hud_weather">Weather</string>
  <string string_id="panel_inventory">Inventory</string>
  <string string_id="panel_build">Build</string>
  <string string_id="panel_inspect">Inspect</string>
  <string string_id="action_harvest">Harvest</string>
  <string string_id="action_water">Water</string>
  <string string_id="action_till">Till</string>
  <string string_id="action_dig">Dig</string>
  <string string_id="action_rake">Rake</string>
  <string string_id="action_uproot">Uproot</string>
  <string string_id="action_prune">Prune</string>
  <string string_id="tool_hoe">Hoe</string>
  <string string_id="tool_rake">Rake</string>
  <string string_id="tool_watering_can">Watering can</string>
  <string string_id="tool_scythe">Scythe</string>
  <string string_id="tool_shovel">Shovel</string>
  <string string_id="surface_bare_soil">Bare soil</string>
  <string string_id="surface_tilled">Tilled soil</string>
  <string string_id="surface_mulch">Mulch</string>
  <string string_id="surface_rock">Rock</string>
  <string string_id="surface_sand">Sand</string>
  <string string_id="season_spring">Spring</string>
  <string string_id="season_summer">Summer</string>
  <string string_id="season_autumn">Autumn</string>
  <string string_id="season_winter">Winter</string>
  <string string_id="weather_clear">Clear</string>
  <string string_id="weather_rain">Rain</string>
  <string string_id="weather_storm">Storm</string>
  <string string_id="weather_drizzle">Drizzle</string>
  <string string_id="weather_heatwave">Heatwave</string>
  <string string_id="weather_overcast">Overcast</string>
</ui_strings>
